AWSTemplateFormatVersion: '2010-09-09'
Description: Share Repository

Parameters:

  DomainName:
    Description: Full domain name this service should be reachable by
    Type: String

  CertificateArn:
    Description: Certificate ARN from region "us-east-1" to secure calls via the domain name above
    Type: String
    AllowedPattern: arn:aws:acm:us-east-1:.+
    ConstraintDescription: must be located in region "us-east-1" (start with "arn:aws:acm:us-east-1:")

  BucketNamePrefix:
    Description: Prefixes the bucket name (stack name + ...) by a string
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Webservice Configuration
        Parameters:
          - DomainName
          - CertificateArn
      - Label:
          default: Storage Configuration
        Parameters:
          - BucketNamePrefix

Resources:

  Storage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}${AWS::StackName}-storage"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SiteIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${AWS::StackName}-site-identity"
  StorageReaderPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Storage
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Principal:
              AWS: !Join ["", ["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ", !Ref SiteIdentity]]
            Resource: !Join ["", ["arn:aws:s3:::", !Ref Storage, "/*"]]
  SiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Sub ${DomainName}
        DefaultCacheBehavior:
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          Compress: true
          DefaultTTL: 0
          ForwardedValues:
            QueryString: true
          TargetOriginId: Site
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt Storage.RegionalDomainName
          Id: Site
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${SiteIdentity}"
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only