name: Create Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        version=$(cat "version")
        curl -L "https://github.com/cube-codes/cube-codes-framework/releases/download/${version}/cube-codes-ide-${version}-web.zip" -o "web.zip"
        unzip web.zip
        aws --version
        ls -laR
#
# Download web archive
# Unzip archive
# Delete from S3 everything that is not a version folder
# Upload everything
# - Set Cache for version folder
# - Set No-Cache for else